### ISSUE TITLE
#REQ-01 Criar DTOs de request e response para cadastro de um novo lote

### ISSUE THREAD

**Issue by vinidomeli** [vinidomeli/tlm-frescos-api#10]
### Importante
Lembrar de criar as validações de inputs

**Comment by vinidomeli** [comment]
START: 01/07/2021 as 17:41

**Comment by andradeirla** [comment]
Início: 02/07/2021 às 8h45
Pausa para o requisito 2: 9h às 9h30
Fim: 02/07/2021 às 10h20
