### ISSUE TITLE
#REQ-02 Atualizar DER e MER com dados do requisito 2

### ISSUE THREAD

**Issue by andradeirla** [vinidomeli/tlm-frescos-api#26]

**Comment by gdeandradero** [comment]
[DER_MER_PROJETO_FINAL.zip](https://github.com/vinidomeli/tlm-frescos-api/files/6764964/DER_MER_PROJETO_FINAL.zip)

**Comment by gdeandradero** [comment]
![DER](https://user-images.githubusercontent.com/84413927/124485024-86ae7800-dd82-11eb-91a1-37ab38c7777d.png)

**Comment by gdeandradero** [comment]
![MER](https://user-images.githubusercontent.com/84413927/124487383-050c1980-dd85-11eb-87c0-70258d15ff27.png)
