### ISSUE TITLE
Criar diagrama de entidades do banco

### ISSUE THREAD

**Issue by vinidomeli** [vinidomeli/tlm-frescos-api#5]

**Comment by luana-ogawa** [comment]
[diagramas_projeto_final_bootcamp.zip](https://github.com/vinidomeli/tlm-frescos-api/files/6750096/diagramas_projeto_final_bootcamp.zip)

<img width="1259" alt="DER" src="https://user-images.githubusercontent.com/84414178/124173244-2917e400-da81-11eb-8f4f-401c2cc62dc0.png">
<img width="1155" alt="MER" src="https://user-images.githubusercontent.com/84414178/124173254-2cab6b00-da81-11eb-8afa-260e20dcaef9.png">

**Comment by vinidomeli** [comment]
É importante termos o userID no produto e o supervisorID no warehouse

**Comment by luana-ogawa** [comment]
[Diagramas_Projeto_Final_Bootcamp.zip](https://github.com/vinidomeli/tlm-frescos-api/files/6750461/Diagramas_Projeto_Final_Bootcamp.zip)

<img width="1251" alt="DER" src="https://user-images.githubusercontent.com/84414178/124181722-47371180-da8c-11eb-9c83-af9d647d31ab.png">

<img width="1091" alt="MER" src="https://user-images.githubusercontent.com/84414178/124181709-43a38a80-da8c-11eb-9ef8-0213909cf7fd.png">
